### PR TITLE
Do not strip whitespace from whitespace-only lines

### PR DESCRIPTION
**Pull request by CupOfTea696**
When using the indent guides extension, the indents get interrupted if whitespace-only lines get stripped of their whitespace. It looks really disturbing and this fixes that issue. 

screen shot 2014-10-30 at 19 41 24

### CODE REVIEW

**Comment by hamdanjaveed** [comment]
Looks good, I'll update the extension when I get the time

**Comment by CupOfTea696** [comment]
Thanks!

**Comment by cheesypoof** [comment]
I quite like the current behavior... Perhaps support for a brackets.json setting could be added to make this change optional?

**Comment by CupOfTea696** [comment]
I don't really know how to work with extensions but if any one else feels like making this a setting, sure!

**Pull request merged**
